# Site settings
title: Justin Maslin
email: contact@justinmaslin.com
timezone: America/New_York
description: >
  Student, developer, food truck enthusiast! 
  A blog about the life of someone who likes breakfast a little too much.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justinmaslin.com" # the base hostname & protocol for your site
# twitter_username: justinmaslin
github_username:  jmaslin
linkedin_username: justinmaslin

lastupdated: Nov 5 2014

# Build settings
markdown: kramdown
