# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Justin Maslin
tagline:          'Blog like it is 1999.'
description:      'Business student, web developer, and aspiring entrepreneur.'
url:              http://justinmaslin.com
baseurl:          /

author:
  name:           'Justin Maslin'
  email:          'web@justinmaslin.com'
  linkedin:				'justinmaslin'

paginate:         5

# Custom vars
# version:          2.1.0

github:
  name:						'jmaslin'
  # repo:           https://github.com/jmaslin
